export const OnRampErrorType = {
  AMOUNT_TOO_LOW: 'INVALID_AMOUNT_TOO_LOW',
  AMOUNT_TOO_HIGH: 'INVALID_AMOUNT_TOO_HIGH',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INCOMPATIBLE_REQUEST: 'INCOMPATIBLE_REQUEST',
  BAD_REQUEST: 'BAD_REQUEST',
  NO_VALID_QUOTES: 'NO_VALID_QUOTES',
  FAILED_TO_LOAD: 'FAILED_TO_LOAD',
  FAILED_TO_LOAD_COUNTRIES: 'FAILED_TO_LOAD_COUNTRIES',
  FAILED_TO_LOAD_PROVIDERS: 'FAILED_TO_LOAD_PROVIDERS',
  FAILED_TO_LOAD_METHODS: 'FAILED_TO_LOAD_METHODS',
  FAILED_TO_LOAD_CURRENCIES: 'FAILED_TO_LOAD_CURRENCIES',
  FAILED_TO_LOAD_LIMITS: 'FAILED_TO_LOAD_LIMITS',
  UNKNOWN: 'UNKNOWN_ERROR'
} as const;

export type OnRampErrorTypeValues = (typeof OnRampErrorType)[keyof typeof OnRampErrorType];

export interface OnRampError {
  type: OnRampErrorTypeValues;
  message: string;
}
