enableImmutableInstalls: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

# Enable patch protocol for applying patches automatically
enableGlobalCache: false
patchFolder: patches
