blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/orgs/reown-com/discussions/categories/web3modal-sdk-support
    about: Looking for help with your app? Please refer to the Reown community's support resources.
