name: UI Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to use'
        default: 'main'
        required: false
        type: string
      base-url:
        description: 'The AppKit App url'
        default: 'http://localhost:8081/'
        required: false
        type: string
      wallet-url:
        description: 'The wallet url'
        default: 'https://react-wallet.walletconnect.com/'
        required: false
        type: string
      command:
        description: 'The test command to run'
        default: 'playwright:test'
        required: false
        type: string
      skip-playwright-webserver:
        description: 'Skip setting up a local test server'
        default: false
        required: false
        type: boolean
    secrets:
      CLOUD_PROJECT_ID:
        required: true

jobs:
  ui_tests:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    steps:
      # Possibly this helps with GitHub-hosted runner network issues, but it's not confirmed
      # It's not supported in self-hosted runners, however, so commenting it out for now
      # - name: Tune GitHub-hosted runner network
      #   uses: smorimoto/tune-github-hosted-runner-network@v1

      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: reown-com/appkit-react-native
          ref: ${{ inputs.branch }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create ENV file in apps/native
        run: cd apps/native && echo "EXPO_PUBLIC_PROJECT_ID=$CLOUD_PROJECT_ID" >> .env

      - name: Start Expo Web and Run Tests
        working-directory: ./apps/native/
        env:
          BASE_URL: ${{ inputs.base-url }}
          WALLET_URL: ${{ inputs.wallet-url }}
          CLOUD_PROJECT_ID: ${{ secrets.CLOUD_PROJECT_ID }}
          SKIP_PLAYWRIGHT_WEBSERVER: ${{ inputs.skip-playwright-webserver }}
          CI: true
        run: |
          # Start the Expo web server in the background
          yarn web & 

          # Wait for the server to be ready
          echo "Waiting for Expo web server to be ready..."
          timeout=300  # 5 minutes timeout
          start_time=$(date +%s)
          while ! curl -s http://localhost:8081 > /dev/null; do
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))
            if [ $elapsed -gt $timeout ]; then
              echo "Timeout waiting for Expo web server"
              exit 1
            fi
            sleep 2
          done
          echo "Expo web server is ready!"

          # Run the Playwright tests
          yarn ${{ inputs.command }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-${{ matrix.shard }}
          path: ./apps/native/playwright-report/
          retention-days: 7
