name: Expo Preview

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  preview:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create .env file in native app
        run: |
          cd apps/native && echo "EXPO_PUBLIC_PROJECT_ID=$EXPO_PUBLIC_PROJECT_ID" >> .env
        shell: bash
        env:
          EXPO_PUBLIC_PROJECT_ID: ${{ secrets.CLOUD_PROJECT_ID }}

      - name: Create preview
        id: preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --branch preview
          comment: true
          working-directory: apps/native
        env:
          EXPO_PUBLIC_PROJECT_ID: ${{ secrets.CLOUD_PROJECT_ID }}
