name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Build
        run: yarn build

      - name: Package Tests
        run: yarn test

  e2e:
    needs: pre-publish
    uses: ./.github/workflows/e2e.yml@${{ github.ref }}
    secrets:
      CLOUD_PROJECT_ID: ${{ secrets.CLOUD_PROJECT_ID }}
    with:
      skip_setup: true
