name: Verify
on:
  workflow_call:
    secrets:
      CLOUD_PROJECT_ID:
        required: true
  workflow_dispatch:

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Build
        run: yarn build

      - name: Package Tests
        run: yarn test

      - name: E2E Tests
        uses: ./.github/workflows/e2e.yml
        secrets:
          CLOUD_PROJECT_ID: ${{ secrets.CLOUD_PROJECT_ID }}
        with:
          skip_setup: true
