name: Verify

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Build
        run: yarn build

      - name: Package Tests
        run: yarn test
